### ISSUE TITLE
Missing depth-anything

### ISSUE THREAD

**Issue by ChaoyueSong** [MegaScenes/nvs#1]
Hi, thanks for your great work.

You may miss depth-anything in your repo.
```
submodule_path = ( "/share/phoenix/nfs05/S8/gc492/scene_gen/Depth-Anything" )
assert os.path.exists(submodule_path)
```

**Comment by gene-chou** [comment]
Thanks for catching this. You will need to remove those lines and install depth anything yourself following their [repo](https://github.com/LiheYoung/Depth-Anything).
